from typing import Any, Dict, Iterator, List, Optional, Tuple, Union

class Struct(dict[str, Any]):
    """Dynamic dict supporting attribute-style dot notation (e.g., struct.reward)."""
    action: Any
    info: Any
    observation: Struct | Dict[str, Any]
    reward: Optional[float]
    status: str
    seed: Optional[int]

    def __init__(self, **entries: Any) -> None: ...
    def __getattr__(self, attr: str) -> Any: ...
    def __setattr__(self, attr: str, value: Any) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __contains__(self, key: object) -> bool: ...
    def get(self, key: str, default: Any = None) -> Any: ...

def structify(obj: Any) -> Any: ...
def unstructify(obj: Any) -> Any: ...

envs_path: str
schemas: Dict[str, Any]
